serverconf works on localhost and remote

diff --git a/bin/serverconf b/bin/serverconf
--- a/bin/serverconf
+++ b/bin/serverconf
@@ -1,6 +1,7 @@
 #!/bin/sh -e
 
 INIT_URL="https://bitbucket.org/hazelnut/serverconf/raw/master/src/host-init.sh"
+INIT_ARGS=''
 
 print_help () {
   echo "Initialize a newly created FreeBSD remote server." >&2;
@@ -12,8 +13,8 @@ print_help () {
 
 while getopts "U:P:k:h" opt; do
   case $opt in
-    U) REPO_USER="$OPTARG";;
-    P) REPO_PASS="$OPTARG";;
+    U) REPO_USER="$OPTARG"; INIT_ARGS="$INIT_ARGS -U '$OPTARG'";;
+    P) REPO_PASS="$OPTARG"; INIT_ARGS="$INIT_ARGS -U '$OPTARG'";;
     k) PUBKEY="$OPTARG";;
     h) print_help; exit 0;;
     \?) print_help; exit 1;;
@@ -28,40 +29,69 @@ if [ -z "$HOST_NAME" ]; then
   exit 1
 fi
 
+#convert local ssh pub key file to string to pass as host-init parameter
+if [ -f "$PUBKEY" ]; then PUBKEY="$(cat $PUBKEY)"; fi
+if [ -n "$PUBKEY" ]; then INIT_ARGS="$INIT_ARGS -k '$PUBKEY'"; fi
+
+
+# Need the repo info here so we can download from the auth url
 repo_host=$(echo "$INIT_URL" | awk -F/ '{print $3}')
 
 if [ -z "$REPO_USER" ]; then
   read -p "'$repo_host' username: " REPO_USER
+  INIT_ARGS="$INIT_ARGS -U '$REPO_USER'"
 fi
 
 if [ -z "$REPO_PASS" ]; then
   stty -echo
   read -p "'$repo_host' password: " REPO_PASS; echo
   stty echo
+  INIT_ARGS="$INIT_ARGS -P '$REPO_PASS'"
 fi
-
-#convert local ssh pub key file to string to pass as host-init parameter
-if [ -f "$PUBKEY" ]; then
-  PUBKEY="$(cat $PUBKEY)"
-fi
-
-## Set up commands to run on remote server.
-## Root shell defaults to csh.
 
 repo_auth_url="https://$REPO_USER:$REPO_PASS@${INIT_URL#*//}"
-init_file="/tmp/$(basename $INIT_URL)"
 
-su_msg="sh -c 'if [ \$(id -u) != 0 ]; then echo -n \"Must run as superuser. \"; fi'"
 
-#new install doesn't have any ssl certificates
-#need to spoof user-agent because of bitbucket problem
-get_file="fetch -q --no-verify-peer --user-agent 'Wget/1.16' -o $init_file $repo_auth_url"
+# Run as $USER
+syscheck_script="sh -e -c '
 
-check_file="if (! -e $init_file) echo \"Unable to run install script, aborting.\""
+if [ \$(uname -s) != '\"FreeBSD\"' ]; then
+  echo '\"This script can only configure a FreeBSD server.\"';
+  exit 1;
+fi
 
-run_file="if (-e $init_file) sh -e $init_file -U $REPO_USER -P $REPO_PASS -k \"$PUBKEY\""
+if [ \$(id -u) != 0 ];
+  then echo -n \"Must run as superuser. \";
+fi
+'"
 
-del_file="if (-e $init_file) rm $init_file"
+#pseudo-distinct filename to store the downloaded bootstrap script
+init_file="/tmp/$(basename $INIT_URL).$(date +%s)"
 
-# and ... go!
-ssh -X -t -t "$HOST_NAME" "$su_msg; su - root -f -c '$get_file; $check_file; $run_file; $del_file;'"
+# Run as root
+# This kind of escaping is painful and error prone, do as little as possible.
+# Do not create vars in here, just access external ones on the first substition.
+# To quote strings use: '\"my string\"'
+init_script="su - root -f -c 'sh -e -c \"
+
+if ! fetch -q --no-verify-peer --user-agent '\"Wget/1.16\"' -o $init_file '\"$repo_auth_url\"'; then
+  echo '\"Error downloading $init_file, exiting.\"';
+  exit 1;
+
+else
+  if [ -e $init_file ]; then
+    sh -e $init_file '\"$INIT_ARGS\"';
+  else
+    echo Unable to find init script, exiting.;
+    exit 1;
+  fi
+fi
+\" ' "
+
+
+# Run local or remote
+if [ "$HOST_NAME" == 'localhost' -o "$HOST_NAME" == '127.0.0.1' -o "$HOST_NAME" == '::1' ]; then
+  sh -e -c "$syscheck_script; $init_script;"
+else
+  ssh -X -t -t "$HOST_NAME" "$syscheck_script; $init_script;"
+fi
