THe real serverconf for remote and local usage.

diff --git a/bin/serverconf b/bin/serverconf
--- a/bin/serverconf
+++ b/bin/serverconf
@@ -1,22 +1,20 @@
 #!/bin/sh -e
 
 INIT_URL="https://bitbucket.org/hazelnut/serverconf/raw/master/src/host-init.sh"
-INIT_ARGS=''
-APP_ROOT="$(cd $(dirname $(dirname $0)) && pwd -P)"
+PUBKEY_DEFAULT='~/.ssh/id_rsa.pub'
 
 print_help () {
   echo "Initialize a newly created FreeBSD remote server." >&2;
   echo "Usage: $(basename $0) [options] host" >&2;
-  echo " -k=pubkey    Public key for host's app user" >&2;
+  echo " -k=pubkey    Public key for remote setup [$PUBKEY_DEFAULT]" >&2;
   echo " -U=username  Repo user (https://bitbucket.org/hazelnut/serverconf)" >&2;
   echo " -P=password  Repo user password" >&2;
 }
 
-
 while getopts "U:P:k:h" opt; do
   case $opt in
-    U) REPO_USER="$OPTARG"; INIT_ARGS="$INIT_ARGS -U \"$OPTARG\"";;
-    P) REPO_PASS="$OPTARG"; INIT_ARGS="$INIT_ARGS -U \"$OPTARG\"";;
+    U) REPO_USER="$OPTARG";;
+    P) REPO_PASS="$OPTARG";;
     k) PUBKEY="$OPTARG";;
     h) print_help; exit 0;;
     \?) print_help; exit 1;;
@@ -31,96 +29,107 @@ if [ -z "$HOST_NAME" ]; then
   exit 1
 fi
 
+repo_host=$(echo "$INIT_URL" | awk -F/ '{print $3}')
 
-
-##
-## Bootstrap
-##
-
-bootstrap_src='
-echo "--->$INIT_FILE $INIT_URL"
-if [ $(uname -s) != "FreeBSD" ]; then
-  echo "This script can only configure a FreeBSD server."
-  exit 1;
+if [ -z "$REPO_USER" ]; then
+  echo "Need to download setup:"
+  read -p "'$repo_host' username: " REPO_USER
 fi
 
-if ! fetch -q --no-verify-peer --user-agent "Wget/1.16" -o "$INIT_FILE" "$INIT_URL"; then
-  echo "Error downloading $INIT_FILE, exiting.";
-  exit 1;
+if [ -z "$REPO_PASS" ]; then
+  stty -echo
+  read -p "'$repo_host' password: " REPO_PASS; echo
+  stty echo
+fi
 
-else
-  if [ -e $INIT_FILE ]; then
-    if [ $(id -u) != 0 ]; then
-      echo -n "Must run as superuser. "
-    fi
-    su - root -f -c "sh -e $INIT_FILE \"$INIT_ARGS\""
-  else
-    echo "Unable to find init script, exiting.";
-    exit 1;
-  fi
-fi'
-
-su_prompt='if [ `id -u` != 0 ]; then echo -n "Must run as superuser. "; fi'
+init_url="https://$REPO_USER:$REPO_PASS@${INIT_URL#*//}"
+init_args="$init_args -U \"$REPO_USER\" -P \"$REPO_PASS\""
 
 ##
-## Run locally. Don't need the entire repo, this script will bootstrap.
+## If run locally, download the host-init script and run as root.
 ##
 
 if [ "$HOST_NAME" == 'localhost' -o "$HOST_NAME" == '127.0.0.1' -o "$HOST_NAME" == '::1' ]; then
 
-	if [ $(uname -s) != "FreeBSD" ]; then
-		echo "This script can only configure a FreeBSD server."  >&2
-		exit 1;
-	fi
+  if [ $(uname -s) != "FreeBSD" ]; then
+    echo "This script can only configure a FreeBSD server."  >&2
+    exit 1;
+  fi
 
-	init_file=$(mktemp -t $(basename "$INIT_URL"))
-	bootstrap_file=$(mktemp -t $(basename "$init_file-bootstrap"))
-	echo "$bootstrap_src" > "$bootstrap_file"
+  init_file=$(mktemp -t $(basename "$INIT_URL"))
 
-	sh -e -c "$su_prompt"
-	su - root -c "env INIT_FILE='$init_file' INIT_URL='$init_url' sh -e $bootstrap_file"
-	rm "$bootstrap_file" "$init_file"
-	exit 0
+  if ! fetch -q --no-verify-peer --user-agent 'Wget/1.16' -o "$init_file" "$init_url"; then
+    echo "Error downloading $init_file, exiting.";
+    exit 1;
+  else
+    if [ -e "$init_file" ]; then
+      if [ $(id -u) != 0 ]; then
+        echo -n "Must run as superuser. "
+      fi
+      #su_prompt='if [ `id -u` != 0 ]; then echo -n "Must run as superuser. "; fi'
+      su - root -f -c "sh -e $init_file $init_args"
+    else
+      echo "Unable to find init script, exiting.";
+      exit 1;
+    fi
+  fi
+
+  #cleanup
+  rm "$init_file"
+  #if we key authenticated as root, remove that
+  if [ $(id -u) == 0 -a -f '/root/.ssh/authorized_keys' ]; then
+    rm -rf '/root/.ssh/authorized_keys'
+  fi
+
+  exit 0
 fi
 
 ##
-## Run remote.
+## Running remotely. Configure ssh key auth, if needed.
 ##
 
-#if we already have a pubkey connection then skip adding it
 if ! ssh -q -o 'BatchMode=yes' "$HOST_NAME" true; then
 
-	#convert local ssh pub key file to string to pass as host-init parameter
-	if [ ! -f "$PUBKEY" ]; then
-		pubkeystr="$PUBKEY"
-		PUBKEY=$(mktemp -t 'pubkey')
-		echo "$pubkeystr" > "$PUBKEY"
-	fi
+  if [ -n "$PUBKEY" -a ! -f "$PUBKEY" ]; then
+    #if given key string, make it a temp file
+    pubkeystr="$PUBKEY"
+    PUBKEY=$(mktemp -t 'pubkey')
+    echo "$pubkeystr" > "$PUBKEY"
 
-	#check fingerprint to make sure it's a valid key
-	if ! ssh-keygen -l -f "$PUBKEY" > /dev/null; then
-		echo "Invalid public key, not adding, and exiting." >&2;
-		exit 1
-	else
-		pubkeystr=$(cat "$PUBKEY")
-		keyfile='~/.ssh/authorized_keys'
-		echo "Adding pubkey to authorized key"
-		if ! ssh "$HOST_NAME" "mkdir -p -m 700 ~/.ssh; echo $pubkeystr >> $keyfile; chmod 600 $keyfile;" >/dev/null 2>&1; then
-			echo "Unable to add key, exiting."
-			exit 1
-		fi
-	fi
+  elif [ -z "$PUBKEY" ]; then
+    #if no key, prompt
+    read -p "Use public ssh key [$PUBKEY_DEFAULT]: " PUBKEY
+    if [ -z "$PUBKEY" ]; then PUBKEY="$PUBKEY_DEFAULT"; fi
+    PUBKEY=$(eval echo "$PUBKEY") #expand tilde
+
+    if [ ! -f "$PUBKEY" ]; then
+      echo "Invalid file: $PUBKEY, exiting." >&2;
+      exit 1
+    fi
+  fi
+
+  #check fingerprint to make sure it's a valid key
+  if ! ssh-keygen -l -f "$PUBKEY" > /dev/null; then
+    echo "Invalid key, exiting and not adding." >&2;
+    exit 1
+  else
+    #log in to remote and add to authorized keys
+    pubkeystr=$(cat "$PUBKEY")
+    keyfile='~/.ssh/authorized_keys'
+
+    if ! ssh "$HOST_NAME" "mkdir -p -m 700 ~/.ssh; echo $pubkeystr >> $keyfile; chmod 600 $keyfile;" >/dev/null 2>&1; then
+      echo "Unable to add key to $HOST_NAME:$keyfile, exiting." >&2;
+      exit 1
+    else
+      echo "Added key to $HOST_NAME:$keyfile"
+    fi
+  fi
 fi
 
+##
+## Auth ready. Upload this script and run locally.
+##
 
-init_file="$(ssh -q $HOST_NAME mktemp -t $(basename $INIT_URL))"
-bootstrap_file="$(ssh -q $HOST_NAME mktemp -t $(basename $init_file-bootstrap))"
-
-bootstrap_file_local=$(mktemp -t $(basename "$bootstrap_file"))
-echo "$bootstrap_src" > "$bootstrap_file_local"
-
-scp -q "$bootstrap_file_local" "$HOST_NAME:$bootstrap_file"
-
-ssh -t "$HOST_NAME" "sh -e -c '$su_prompt'; su - root -c 'env INIT_FILE=\"$init_file\" INIT_URL=\"$init_url\" sh -e $bootstrap_file'; rm $bootstrap_file $init_file;"
-
-rm "$bootstrap_file_local"
+remote_init="$(ssh -q $HOST_NAME mktemp -t $(basename $0))"
+scp -q "$0" "$HOST_NAME:$remote_init"
+ssh -t "$HOST_NAME" "sh -e $remote_init $init_args localhost"
