Initial working skeleton for jailupdate. Calls all the hooks.

diff --git a/host/usr/local/sbin/jailcreate b/host/usr/local/sbin/jailcreate
--- a/host/usr/local/sbin/jailcreate
+++ b/host/usr/local/sbin/jailcreate
@@ -1,12 +1,10 @@
 #!/bin/sh -e
 ## Create an empty jail and set its environment.
-##
-## The jail's ezjail.flavour script is automatically run within the
-## jail when it is first started.
-## This script checks for the jail-create.preinit and jail-create.postinit
-## files located in the flavor directory. These are run from the host.
+## This script looks for the file hooks: preinit, init, and postinit,located within
+## the jail type directory.
+## Preinit and postinit are run on the host system, init is run within the jail itself.
 
-#shoud be something like /usr/local/opt/kola
+#shoud be something like /usr/local/opt/serverconf
 APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
 #add current user to jail by default (even if sudo'd)
 JAIL_USER="$(who -m | cut -d ' ' -f1)"
@@ -14,9 +12,9 @@ JAIL_USER="$(who -m | cut -d ' ' -f1)"
 print_help () {
   echo "Usage: $(basename $0) [options]" >&2;
   echo "Options:" >&2;
+  echo " -j=id      Id of jail" >&2;
   echo " -i=ipaddr  Address to bind jail" >&2;
   echo " -t=type    Jail type (see $APP_ROOT/jails)" >&2;
-  echo " -j=id      Id of jail [default is type]" >&2;
   echo " -u=user    Add user to jail [default is current user]" >&2;
   echo " -h         Print this help message" >&2;
 }
@@ -28,7 +26,7 @@ fi
 
 ## Parse options
 
-while getopts "j:i:t:u:" opt; do
+while getopts "j:i:t:u:h" opt; do
   case $opt in
     j) JAIL_ID="$OPTARG";;
     i) JAIL_IP="$OPTARG";;
@@ -97,6 +95,16 @@ jail_hook () {
 
 ezjail-admin create "$JAIL_ID" "$JAIL_IP"
 
+# add config vars that can be reached within the jail
+jailconf="/usr/jails/$JAIL_ID/etc/serverconf"
+
+if [ ! -f "$jailconf" ]; then touch "$jailconf"; fi
+
+if ! sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype" -v "$JAIL_TYPE"; then
+  echo "$(basename $0): Error setting jail config file, exiting." >&2
+  exit 1
+fi
+
 ## Preinit
 ## Modify config dir before copying into jail.
 
@@ -132,6 +140,8 @@ fi
 ## Postinit
 
 jail_hook 'postinit' 'host'
+
+echo "Restarting jail ..."
 
 ezjail-admin restart "$JAIL_ID"
 
diff --git a/host/usr/local/sbin/jailupdate b/host/usr/local/sbin/jailupdate
--- a/host/usr/local/sbin/jailupdate
+++ b/host/usr/local/sbin/jailupdate
@@ -1,2 +1,73 @@
 #!/bin/sh
-echo "Not implemented"
+
+APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
+
+print_help () {
+  echo "Usage: $(basename $0) jailname" >&2;
+}
+
+if [ $(id -u) != 0 ]; then
+  echo "This script must be run as root." 1>&2
+  exit 1
+fi
+
+## Parse args and get jail environmental vars
+
+for lastarg; do true; done
+JAIL_ID="$lastarg"
+
+if [ -z "$JAIL_ID" ]; then print_help; exit 1; fi
+
+jailconf="/usr/jails/$JAIL_ID/etc/serverconf"
+
+if [ ! -f "$jailconf" ]; then
+  JAIL_TYPE="default"
+else
+  JAIL_TYPE=$(sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype")
+  if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE="default"; fi
+fi
+
+#ezjail-admin lists all installed jails, running or not
+jail_rec=$(ezjail-admin list | tail -n +3 | grep "\b$JAIL_ID\b")
+
+if [ -n "$jail_rec" ]; then
+  JAIL_IP=$(echo "$jail_rec" | awk '{print $3}')
+else
+  echo "$(basename $0): Jail '$JAIL_ID' is not installed, exiting." >&2;
+  exit 1
+fi
+
+if [ $(echo "$jail_rec" | awk '{print $2}') != 'N/A' ]; then
+  JAIL_UP=1
+fi
+
+## Helper functions
+
+jail_hook () {
+  local hookname="$1" hookenv="$2"
+  env JAIL_ID="$JAIL_ID" \
+      JAIL_IP="$JAIL_IP" \
+      JAIL_TYPE="$JAIL_TYPE" \
+      sh -e "$APP_ROOT/src/jail-hook.sh" "$hookname" "$hookenv"
+}
+
+## And off we go ...
+
+if [ -z "$JAIL_UP" ]; then
+  echo "Jail is not currently running, required for update ..."
+  if ! ezjail-admin start "$JAIL_ID"; then
+    echo "$(basename $0): Unable to start jail '$JAIL_ID', exiting" >&2
+    exit 1
+  fi
+fi
+
+jail_hook 'preupdate' 'host'
+
+jail_hook 'update' 'jail'
+
+jail_hook 'preupdate' 'host'
+
+if [ -z "$JAIL_UP" ]; then
+  echo "Update complete. Returning jail to stopped state ..."
+  ezjail-admin stop "$JAIL_ID"
+fi
