Getting jailsave/jailrestore right.

diff --git a/host/usr/local/sbin/jailconf b/host/usr/local/sbin/jailconf
--- a/host/usr/local/sbin/jailconf
+++ b/host/usr/local/sbin/jailconf
@@ -10,10 +10,10 @@ APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
 JAIL_USER="$(who -m | cut -d ' ' -f1)"
 
 print_help () {
-  echo "Usage: $(basename $0) [options]" >&2;
+  echo "Usage: $(basename $0) [options] -i=ipaddr" >&2;
+  echo " -i=ipaddr  Address to bind jail" >&2;
   echo "Options:" >&2;
   echo " -n=name    Name of jail" >&2;
-  echo " -i=ipaddr  Address to bind jail" >&2;
   echo " -t=type    Jail type (see $APP_ROOT/jails)" >&2;
   echo " -u=user    Add user to jail [default is current user]" >&2;
   echo " -h         Print this help message" >&2;
@@ -32,21 +32,22 @@ while getopts "n:i:t:u:h" opt; do
   esac
 done
 
-if [ -z "$JAIL_IP" ]; then print_help; exit 1; fi
+if [ $(id -u) != 0 ]; then
+  echo "$(basename $0): This script must be run as root." 1>&2
+  exit 1
+fi
 
 if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE='default'; fi
 
-if [ $(id -u) != 0 ]; then
-  echo "This script must be run as root." 1>&2
-  exit 1
-fi
-
 if [ ! -d "$APP_ROOT/jails/$JAIL_TYPE" ]; then
-  echo "Jail type '$JAIL_TYPE' doesn't exist, aborting." >&2
+  echo "$(basename $0): Jail type '$JAIL_TYPE' doesn't exist, aborting." >&2
   exit 1
 fi
 
-if jls -v | grep "$JAIL_IP" > /dev/null; then
+if [ -z "$JAIL_IP" ]; then
+  print_help
+  exit 1
+elif jls -v | grep "$JAIL_IP" > /dev/null; then
   echo -n "Address $JAIL_IP already used, you may experience network problems." 1>&2
   read -p " Continue? (y/n) " reply
   if [ "$reply" != 'y' -a "$reply" != 'yes' ]; then
@@ -66,6 +67,15 @@ if [ -z "$JAIL_NAME" ]; then
   fi
   JAIL_NAME="${JAIL_TYPE}$jid"
 fi
+
+#ezjail converts all non-alphanums to underscore, we should too
+JAIL_NAME=$(echo -n "$JAIL_NAME" | tr -c '[[:alnum:]]' '_')
+
+if [ -e "/usr/local/etc/ezjail/$JAIL_NAME" ]; then
+  echo "$(basename $0): Jail '$JAIL_NAME' already exists, use a different name." >&2;
+  exit 1
+fi
+
 
 ## Helper functions
 
@@ -95,7 +105,10 @@ jail_hook () {
 
 ## Create
 
-ezjail-admin create "$JAIL_NAME" "$JAIL_IP"
+if ! ezjail-admin create "$JAIL_NAME" "$JAIL_IP"; then
+  echo "$(basename $0): Unable to create jail, aborting." >&2;
+  exit 1
+fi
 
 # add config vars that can be reached within the jail
 jailconf="/usr/jails/$JAIL_NAME/etc/serverconf"
@@ -126,7 +139,10 @@ fi
 
 echo "Configuring jail ..."
 
-ezjail-admin start "$JAIL_NAME"
+if ! ezjail-admin start "$JAIL_NAME"; then
+  echo "$(basename $0): Unable to start jail, aborting." >&2;
+  exit 1
+fi
 
 # Copy jail config to jail after conf has chance to install packages
 
@@ -145,6 +161,9 @@ jail_hook 'postconf' 'host'
 
 echo "Restarting jail ..."
 
-ezjail-admin restart "$JAIL_NAME"
+if ! ezjail-admin restart "$JAIL_NAME"; then
+  echo "$(basename $0): Unable to restart jail, aborting." >&2;
+  exit 1
+fi
 
 echo "$JAIL_NAME jail running on $JAIL_IP"
diff --git a/host/usr/local/sbin/jailrestore b/host/usr/local/sbin/jailrestore
--- a/host/usr/local/sbin/jailrestore
+++ b/host/usr/local/sbin/jailrestore
@@ -1,3 +1,121 @@
-#!/bin/sh
+#!/bin/sh -e
 
-ezjail-admin create -a "$ARCHIVE_FILE"
+APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
+
+print_help () {
+  echo "Usage: $(basename $0) [options] -i=ipaddr jailarchive" >&2;
+  echo " -i=ipaddr  Address to bind jail" >&2;
+  echo "Options:" >&2;
+  echo " -n=name    Name of jail" >&2;
+  echo " -s         Don't start jail when it's restored" >&2;
+  echo " -h         Print this help message" >&2;
+}
+
+## Parse options
+
+while getopts "n:i:sh" opt; do
+  case $opt in
+    n) JAIL_NAME="$OPTARG";;
+    i) JAIL_IP="$OPTARG";;
+    s) NO_START_FLAG=1;;
+    h) print_help; exit 0;;
+    \?) print_help; exit 1;;
+  esac
+done
+
+for lastarg; do true; done
+JAIL_SAVE_FILE="$lastarg"
+
+#just verify it's a file, let ezjail-admin bork on a bad archive
+if [ ! -f "$JAIL_SAVE_FILE" ]; then
+  print_help
+  exit 1
+fi
+
+if [ -z "$NO_START_FLAG" ]; then JAIL_UP=1; fi
+
+#parse name from filename, either in standard format or use basename
+#standard save format: jailname-jailtype-hostname-date.tar.gz
+if [ -z "$JAIL_NAME" ]; then
+  if basename "$JAIL_SAVE_FILE" | grep -E ".+-.+-.+-[0-9]+\." > /dev/null; then
+    JAIL_NAME=$(basename "$JAIL_SAVE_FILE" | cut -d '-' -f1)
+  else
+    save_file_basename=$(basename "$JAIL_SAVE_FILE")
+    JAIL_NAME="${save_file_basename%%.*}" #remove extension
+  fi
+fi
+
+#ezjail converts all non-alphanums to underscore, we should too
+JAIL_NAME=$(echo -n "$JAIL_NAME" | tr -c '[[:alnum:]]' '_')
+
+if [ -e "/usr/local/etc/ezjail/$JAIL_NAME" ]; then
+  echo "$(basename $0): Jail '$JAIL_NAME' already exists, use a different name." >&2;
+  exit 1
+fi
+
+if [ -z "$JAIL_IP" ]; then
+  echo "$(basename $0): Requires an ip address to bind jail on, exiting." >&2;
+  exit 1
+elif jls -v | grep "$JAIL_IP" > /dev/null; then
+  echo -n "Address $JAIL_IP already used, you may experience network problems." 1>&2
+  read -p " Continue? (y/n) " reply
+  if [ "$reply" != 'y' -a "$reply" != 'yes' ]; then
+    exit 0
+  fi
+fi
+
+
+jail_hook () {
+  local hookname="$1" hookenv="$2"
+  env JAIL_NAME="$JAIL_NAME" \
+      JAIL_IP="$JAIL_IP" \
+      JAIL_TYPE="$JAIL_TYPE" \
+      JAIL_USER="$(who -m | cut -d ' ' -f1)" \
+      JAIL_UP="$JAIL_UP" \
+      APP_ROOT="$APP_ROOT" \
+      sh -e "$APP_ROOT/src/jail-hook.sh" "$hookname" "$hookenv"
+}
+
+##
+## CREATE JAIL
+##
+
+if ! ezjail-admin create -a "$JAIL_SAVE_FILE" "$JAIL_NAME" "$JAIL_IP"; then
+  echo "$(basename $0): Unable to create jail from archive, aborting." >&2;
+  exit 1
+fi
+
+##
+## Determine jail type from /etc/serverconf
+##
+
+jailconf="/usr/jails/$JAIL_NAME/etc/serverconf"
+
+if [ -f "$jailconf" ]; then
+  JAIL_TYPE=$(sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype")
+fi
+
+if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE='default'; fi
+
+##
+## RUN HOOKS, START JAIL
+##
+
+jail_hook 'prerestore' 'host'
+
+if [ -z "$NO_START_FLAG" ]; then
+  if ! ezjail-admin start "$JAIL_NAME"; then
+    echo "$(basename $0): Unable to start jail, aborting." >&2;
+    exit 1
+  fi
+fi
+
+jail_hook 'restore' 'jail'
+
+jail_hook 'postrestore' 'host'
+
+if [ -z "$NO_START_FLAG" ]; then
+  echo "Jail restored and running as '$JAIL_NAME'"
+else
+  echo "Jail restored as '$JAIL_NAME'"
+fi
diff --git a/host/usr/local/sbin/jailsave b/host/usr/local/sbin/jailsave
--- a/host/usr/local/sbin/jailsave
+++ b/host/usr/local/sbin/jailsave
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -e
 
 APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
 #ezjail default is /usr/jails/ezjail_archives
@@ -7,13 +7,15 @@ JAIL_SAVE_DIR="$APP_ROOT/saved-jails"
 print_help () {
   echo "Usage: $(basename $0) [options] [jailname]" >&2;
   echo "Options:" >&2;
-  echo " -f      Do not stop a running jail before saving" >&2;
-  echo " -d=dir  Directory to store saved jails [$JAIL_SAVE_DIR]" >&2;
+  echo " -f           Do not stop a running jail before saving" >&2;
+  echo " -d=dir       Directory to save the jail archive [$JAIL_SAVE_DIR]" >&2;
+  echo " -n=filename  File basename for saved jail archive [jailname-conftype-hostname-date]" >&2;
 }
 
-while getopts "d:fh" opt; do
+while getopts "d:n:fh" opt; do
   case $opt in
     d) JAIL_SAVE_DIR="$OPTARG";;
+    n) JAIL_SAVE_NAME="$OPTARG";;
     f) FORCE_FLAG=1;;
     h) print_help; exit 0;;
     \?) print_help; exit 1;;
@@ -26,7 +28,7 @@ JAIL_NAME="$lastarg"
 if [ -z "$JAIL_NAME" ]; then print_help; exit 1; fi
 
 #ezjail-admin lists all installed jails, running or not
-jail_rec=$(ezjail-admin list | tail -n +3 | grep "\b$JAIL_NAME\b")
+jail_rec=$(ezjail-admin list | tail -n +3 | grep "[[:space:]]$JAIL_NAME[[:space:]]")
 
 if [ -n "$jail_rec" ]; then
   JAIL_IP=$(echo "$jail_rec" | awk '{print $3}')
@@ -39,26 +41,76 @@ if [ $(echo "$jail_rec" | awk '{print $2}') != 'N/A' ]; then
   JAIL_UP=1
 fi
 
+jailconf="/usr/jails/$JAIL_NAME/etc/serverconf"
+
+if [ -f "$jailconf" ]; then
+  JAIL_TYPE=$(sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype")
+fi
+
+if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE='default'; fi
+
+if [ -z "$JAIL_SAVE_NAME" ]; then
+  JAIL_SAVE_NAME="${JAIL_NAME}-${JAIL_TYPE}-$(hostname)-$(date +'%Y%m%d%H%M%S')"
+else
+	#ezjail converts all non-alphanums to underscore, we should too
+	JAIL_SAVE_NAME=$(echo -n "$JAIL_SAVE_NAME" | tr -c '[[:alnum:]]' '_')
+fi
 
 if [ ! -d "$JAIL_SAVE_DIR" ]; then
   mkdir -p "$JAIL_SAVE_DIR"
 fi
 
 
+jail_hook () {
+  local hookname="$1" hookenv="$2"
+  env JAIL_NAME="$JAIL_NAME" \
+      JAIL_SAVE_NAME="$JAIL_SAVE_NAME" \
+      JAIL_IP="$JAIL_IP" \
+      JAIL_TYPE="$JAIL_TYPE" \
+      JAIL_USER="$(who -m | cut -d ' ' -f1)" \
+      JAIL_UP="$JAIL_UP" \
+      APP_ROOT="$APP_ROOT" \
+      sh -e "$APP_ROOT/src/jail-hook.sh" "$hookname" "$hookenv"
+}
+
+##
+## RUN HOOKS, SAVE JAIL
+##
+
+jail_hook 'presave' 'host'
+
+jail_hook 'save' 'jail'
+
 if [ -n "$JAIL_UP" -a -z "$FORCE_FLAG" ]; then
   echo "Stopping jail before saving ..."
-  ezjail-admin stop "$JAIL_NAME"
+  if ! ezjail-admin stop "$JAIL_NAME"; then
+    echo "$(basename $0): Unable to stop jail, aborting." >&2;
+    exit 1
+  fi
 fi
 
-# jails should be stopped before running. -f does it while running
-# should the default be to stop, or to exit?
+# jails should be stopped before running unless explictly forced
 if [ -n "$FORCE_FLAG" ]; then
-  ezjail-admin archive -f -d "$JAIL_SAVE_DIR" "$JAIL_NAME"
+  ezjail_args='-f'
+fi
+
+echo -n "Saving jail archive ... "
+
+if ! ezjail-admin archive $ezjail_args -d "$JAIL_SAVE_DIR" -a "$JAIL_SAVE_NAME" "$JAIL_NAME"; then
+  echo -e "\n$(basename $0): Unable to archive jail, aborting." >&2;
+  exit 1
 else
-  ezjail-admin archive -d "$JAIL_SAVE_DIR" "$JAIL_NAME"
+	echo "done"
 fi
 
 if [ -n "$JAIL_UP" -a -z "$FORCE_FLAG" ]; then
   echo "Restarting jail ..."
-  ezjail-admin start "$JAIL_NAME"
+  if ! ezjail-admin start "$JAIL_NAME"; then
+    echo "$(basename $0): Unable to start jail, aborting." >&2;
+    exit 1
+  fi
 fi
+
+jail_hook 'postsave' 'host'
+
+echo "Saved jail archive to ${JAIL_SAVE_DIR}/${JAIL_SAVE_NAME}.tar.gz"
