A legit jaildelete

diff --git a/host/usr/local/sbin/jaildelete b/host/usr/local/sbin/jaildelete
--- a/host/usr/local/sbin/jaildelete
+++ b/host/usr/local/sbin/jaildelete
@@ -1,2 +1,81 @@
-#!/bin/sh
-exec ezjail-admin delete -w -f "$@"
+#!/bin/sh -e
+
+APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
+
+print_help () {
+  echo "Usage: $(basename $0) [options] jailname" >&2;
+  echo "Options:" >&2;
+  echo " -h         Print this help message" >&2;
+}
+
+## Parse options
+
+while getopts "h" opt; do
+  case $opt in
+    h) print_help; exit 0;;
+    \?) print_help; exit 1;;
+  esac
+done
+
+for lastarg; do true; done
+JAIL_NAME="$lastarg"
+
+if [ -z "$JAIL_NAME" ]; then print_help; exit 1; fi
+
+if [ ! -e "/usr/local/etc/ezjail/$JAIL_NAME" ]; then
+  echo "$(basename $0): Jail '$JAIL_NAME' doesn't exist, exiting." >&2;
+  exit 1
+fi
+
+#ezjail-admin lists all installed jails, running or not
+jail_rec=$(ezjail-admin list | tail -n +3 | grep "[[:space:]]$JAIL_NAME[[:space:]]")
+
+if [ -n "$jail_rec" ]; then
+  JAIL_IP=$(echo "$jail_rec" | awk '{print $3}')
+else
+  echo "$(basename $0): Jail '$JAIL_NAME' is not installed, exiting." >&2;
+  exit 1
+fi
+
+jailconf="/usr/jails/$JAIL_NAME/etc/serverconf"
+
+if [ -f "$jailconf" ]; then
+  JAIL_TYPE=$(sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype")
+fi
+
+if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE='default'; fi
+
+if jls | tail -n +3 | grep "[[:space:]]$JAIL_NAME[[:space:]]" > /dev/null; then
+  JAIL_UP=1
+fi
+
+
+jail_hook () {
+  local hookname="$1" hookenv="$2"
+  env JAIL_NAME="$JAIL_NAME" \
+      JAIL_IP="$JAIL_IP" \
+      JAIL_TYPE="$JAIL_TYPE" \
+      JAIL_USER="$(who -m | cut -d ' ' -f1)" \
+      JAIL_UP="$JAIL_UP" \
+      APP_ROOT="$APP_ROOT" \
+      sh -e "$APP_ROOT/src/jail-hook.sh" "$hookname" "$hookenv"
+}
+
+
+##
+## RUN HOOKS, DELETE JAIL
+##
+
+jail_hook 'predelete' 'host'
+
+jail_hook 'delete' 'jail'
+
+# -w wipe directory, -f stop jail before deletion
+if ! ezjail-admin delete -w -f "$JAIL_NAME"; then
+  echo "$(basename $0): Unable to delete jail, aborting." >&2;
+  exit 1
+fi
+
+jail_hook 'postdelete' 'host'
+
+echo "Jail '$JAIL_NAME' deleted."
